name: Deploy to EC2

on:
  pull_request:
    branches:
      - master  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Add EC2 host key to known_hosts
      run: ssh-keyscan -t rsa -p 18.216.36.138 >> ~/.ssh/known_hosts

    - name: Deploy project
      run: |
        scp -i $HOME/.ssh/id_rsa -r dist/* ubuntu@18.216.36.138:/usr/share/nginx/html/
